# Generated by Django 5.2.9 on 2026-01-11 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Fichier original')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_size', models.PositiveIntegerField(verbose_name='Taille du fichier (octets)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Type MIME')),
                ('language_detected', models.CharField(blank=True, max_length=10, null=True, verbose_name='Langue détectée')),
                ('pages_count', models.PositiveIntegerField(default=1, verbose_name='Nombre de pages')),
                ('engine_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='Moteur OCR utilisé')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Texte extrait')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Score de confiance')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'upload")),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('failed', 'Échec')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='Texte brut')),
                ('cleaned_text', models.TextField(verbose_name='Texte nettoyé')),
                ('confidence_score', models.FloatField(verbose_name='Score de confiance')),
                ('language_detected', models.CharField(max_length=10, verbose_name='Langue détectée')),
                ('engine_used', models.CharField(max_length=50, verbose_name='Moteur OCR utilisé')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de mots')),
                ('character_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de caractères')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Temps de traitement (secondes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Résultat OCR',
                'verbose_name_plural': 'Résultats OCR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'uploaded_at'], name='documents_d_user_id_5c283c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
    ]
